# Generated by Django 5.2.8 on 2025-12-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presensi',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='presensi',
            name='status_validasi',
            field=models.CharField(choices=[('hadir', 'Hadir'), ('tidak_hadir', 'Tidak Hadir'), ('diluar_lokasi', 'Kehadiran Diluar Lokasi')], default='hadir', max_length=20),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='status',
            field=models.CharField(choices=[('lapor', 'Lapor'), ('ditanggapi', 'Ditanggapi'), ('selesai', 'Selesai')], default='lapor', max_length=20),
        ),
    ]
