# Generated by Django 5.2.8 on 2025-12-08 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_presensi_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('maling', 'Maling'), ('kebakaran', 'Kebakaran'), ('bencana', 'Bencana Alam'), ('keributan', 'Keributan/Tawuran'), ('medis', 'Gawat Darurat Medis'), ('lainnya', 'Lainnya')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Deskripsi tambahan jika kategori Lainnya', null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('active', 'Active'), ('handled', 'Handled/Resolved'), ('false_alarm', 'False Alarm')], default='active', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms_triggered', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms_resolved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
